### ISSUE TITLE
Error on the code

### ISSUE THREAD

**Issue by eth206** [coezbek/office-automation-excel2word-document-properties#1]
Hi Christopher, its an amazing idea and an amazing project that you did work on.
I tried to make it work and read very carefully readme file but somehow im stuck to an error on the VBA code. Do you have any video manual on how to add variables on the docx file and replace them with excel info.

i really hope you can help me out.

all the best

**Comment by coezbek** [comment]
Hey @eth206, could you share your error message? Or screenshot of the error? Good idea about the video.

**Comment by eth206** [comment]
I am not very familiar with VBA so i dont know if i am doing it correctly so i made a video of it:

https://drive.google.com/file/d/1-lEEBGkb5zuZ-kZ-pD-c8dB_Un28rKCY/view?usp=sharing

**Comment by coezbek** [comment]
Thanks for the video! I have spotted your mistake. You need to use the `Name Box` to give a name to the TemplateShape.

I have created an instruction video: https://drive.google.com/file/d/1wEOQolrfbL9VarjhUqftQlNYAHQyLtul/view?usp=sharing and hope this helps.
